spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: order
    password: mysql
  jpa:
    hibernate:
      ddlAuto: update
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka