spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: order
    password: mysql
  jpa:
    hibernate:
      ddlAuto: update
server:
  port: 8082

