spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_service?createDatabaseIfNotExist=true
    username: inventory
    password: mysql
  jpa:
    hibernate:
      ddlAuto: create-drop
server:
  port: 8082

